# Generated by Django 2.0.1 on 2018-01-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0002_reserve_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='reserve_type',
            field=models.IntegerField(blank=True, choices=[(0, '手術'), (1, '検査'), (2, '術前検査'), (3, '診察')], null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='psex',
            field=models.IntegerField(choices=[(0, '男'), (1, '女')]),
        ),
    ]
